### ISSUE TITLE
Publish stable version 1.0.x

### ISSUE THREAD

**Issue by erdembayar** [NuGet/PackageSourceMapper#35]
Currently we're publishing preview version, it's time to publish stable version, then need to update [doc](https://devblogs.microsoft.com/nuget/quickly-map-your-nuget-packages-to-sources).
Changes:
- https://github.com/NuGet/PackageSourceMapper/pull/47
- [Change targetframework from sdk .netcore 3.1 to sdk .net 6.0](https://github.com/NuGet/PackageSourceMapper/pull/41)
- https://github.com/NuGet/PackageSourceMapper/pull/43
- [Allow PackageSourceMapper to report sources that are unused add configure the minimal set](https://github.com/NuGet/PackageSourceMapper/pull/45)

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
Should we include release note or not?

**Comment by nkolev92** [comment]
Given that there's 1 product, as long as the readme is up to date, can we just call that release notes?

**Comment by erdembayar** [comment]
> Given that there's 1 product, as long as the readme is up to date, can we just call that release notes?

Sure. The first two changes are not necessary to call out, as customers would immediately recognize them on nuget.org. The third one is a very minor change. The fourth one is already mentioned in the Readme.md file.

**Comment by nkolev92** [comment]
I'm comfortable with you deciding. 
I think it'd be *nice* to have the release notes, especially since they're probably relatively easy to write, but their value is limited in 1.0, so I wouldn't say we have to do it.

**Comment by erdembayar** [comment]
Published https://www.nuget.org/packages/NuGet.PackageSourceMapper/1.0.415202

**Comment by nkolev92** [comment]
@erdembayar 

The package should ideally have been 1.0.0. 

It's weird that we have a patch number that high.

**Comment by erdembayar** [comment]
> @erdembayar
> 
> The package should ideally have been 1.0.0.
> 
> It's weird that we have a patch number that high.

It increments every time you run the CI pipeline build, that means I had run CI build 3 times before either because of CI pipeline failure or I added something tiny bit code. Probably I could have reset that env var in CI pipeline, anyway it's already out.
Sorry, I'll consider next time. Probably we just release `1.1.x` next time if required.

**Comment by nkolev92** [comment]
The build can probably increment the 4th number, and for the PackageVersion we'd just use the first 3. They can be different. 
Not something we need to do for 1.0, but something we should tweak for 1.1.x if/when that is a thing.
