### ISSUE TITLE
Update target framework from .NET Core 3.1 to .NET 6.0 and publish

### ISSUE THREAD

**Issue by Banner-Keith** [NuGet/PackageSourceMapper#40]
.NET Core 3.1 is no longer supported as of December 13th, 2020. Is there a plan to move to a newer version of .net such as the LTS .net 6.0?

I can't use this tool because of enterprise policies against using software that is beyond its support lifecycle. I'd imagine many companies have the same policy.

**Comment by zivkan** [comment]
@Banner-Keith are you able to clone the repo? `dotnet build` works, no fancy/difficult build scripts, so you could edit the csproj, as I did with this PR: https://github.com/NuGet/PackageSourceMapper/pull/41

Hopefully the relevant people in the team will action the PR and release a new version, but until then it should be easy enough to clone and locally build the tool.

**Comment by Banner-Keith** [comment]
@zivkan I definitely can to get past the issue for now. Just wanted to get it addressed in the source if possible. Thank you for opening a PR.

**Comment by erdembayar** [comment]
Thank you @zivkan for creating the PR to address this. I'll close this issue after publishing the new binaries.

**Comment by erdembayar** [comment]
I have another tracking issue for publishing https://github.com/NuGet/PackageSourceMapper/issues/35, so let's close this one.

**Comment by erdembayar** [comment]
@Banner-Keith 
Please kindly try https://www.nuget.org/packages/NuGet.PackageSourceMapper/1.0.415202, let me know if there's any problem.

**Comment by Banner-Keith** [comment]
@erdembayar Thank you. That works great!
