### ISSUE TITLE
[DCR]: PackageSourceMapper, configure package ID patterns using original casing

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/PackageSourceMapper#8]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

I gave the PackageSourceMapper tool a try on NuGet/Insights and it is awesome! Just have some feedback. When it generates `<package pattern="..." />` XML nodes, would it be possible to use the original casing of package IDs? It would make it more readable and would align with what the tooling does for adding PackageReference (original case is used).

For example, `BuildBundlerMinifier`, `MessagePackAnalyzer`, and `NuGetPackageExplorer` are all a bit harder to read without capitalization.

For reference, I did this manual clean-up in Insights so package IDs match:
https://github.com/NuGet/Insights/commit/71d09e7534ce2e9e7b9699f443a18dc46b0028a8

**Comment by erdembayar** [comment]
@nkolev92 
For getting this original casing info need to make http call to source. Currently tool works offline, this change requires online connection to work, should we add `originalCasing` option instead?

**Comment by zivkan** [comment]
If the package is already in the global packages folder, then no network call is needed. You can read the nuspec from the package directory.
